### ISSUE TITLE
possibility of having traceback in assert_warn or at least log a filename:line number

### ISSUE THREAD

**Issue by ninadmhatre** [assertpy/assertpy#104]
Hi, 

I am planning to use this beautiful lib in my project which has lot of assertion and kind of really messy. with `assert_warn` i can implement fail at last but problem is it hides all the stacktrace.

is there any reason not to provide that? may i submit PR to have an option of getting tb?

```python
# assert_warn(flag).is_true()
assert_warn(flag, with_traceback=True).is_true()

from functools import partial
_assert_warn = partial(assert_warn, with_traceback=True)

# and now i can use it as 
_assert_warn(flag).is_true()
```

**Comment by saturnboy** [comment]
@ninadmhatre By default, `assert_warn` _does_ print the file and line number to `stdout` for all warnings.

For example:

```py
from assertpy import assert_warn

def test_foo():
    assert_warn(1 == 2).is_true()
```

Then run it with (note that `-s` is critical to capture and print `stdout` output while running):

```
pytest -sv foo.py
```

Gives output like:

```
============================= test session starts ==============================
platform darwin -- Python 3.8.1, pytest-5.3.5, py-1.8.1, pluggy-0.13.1, ..

foo.py::test_foo 2020-07-15 09:26:12 WARNING [foo.py:4]: Expected <True>, but was not.
PASSED
```

where `[foo.py:4]` is the filename and line number of the warning.  Is that sufficient?

**Comment by ninadmhatre** [comment]
Hi,

Thanks for replying, my usecase is little different where i will always use
"assert_that" but given certain condition either programmatically or via
setting env variables that will just report all the errors, so code wise
there will be no change just behaviour will change. Adding this to assertpy
felt like abuse of your brilliant API so i created really small library out
of it.

I will try to reason out as well, we check lots of messages with many
fields per message and when we do it against new. App version ond by one
failure is not the fastest way to find out wrong fields so if i can just
run everything in 1 go i will get all the required info.

**Comment by saturnboy** [comment]
One option is to use a [soft assertions](https://github.com/assertpy/assertpy#soft-assertions) context to capture all errors, then output the failures.

But if you really want to control testing via env vars, maybe just rename the import like this:

```py
import os

if os.getenv('ASSERTPY_WARNING') == 'true':
    from assertpy import assert_warn as assert_that
else:
    from assertpy import assert_that
```
