### ISSUE TITLE
Dynamic assertion on dict does not work with an 'update' key

### ISSUE THREAD

**Issue by phillipuniverse** [assertpy/assertpy#105]
Example:

```python
dict = {'update', True}

assert_that(dict).has_update(True)
```

Looks like the call to `get_attr` at https://github.com/assertpy/assertpy/blob/b58ede1726eff5e90a7a2472b02050d7bc2e04cd/assertpy/dynamic.py#L97 returns the dict `update` _method_ instead of the actual attribute contained within the dict.

There is already some checking in this method for `is_dict`, maybe solve this edge case by using that and hardcoding the value retrieval.

**Comment by saturnboy** [comment]
@phillipuniverse thanks for the bug report, fixed exactly as you described

**Comment by phillipuniverse** [comment]
Awesome! Should've just opened the PR myself!
