### ISSUE TITLE
date assertion. need more checks

### ISSUE THREAD

**Issue by maxim-zaitsev** [assertpy/assertpy#106]
Hello!
I am trying to use assertpy to test date filters on web page, using "is_after" and "is_before" methods.
It's ok when after_date is not equal to any date to compare

``` python
from assertpy import assert_that, soft_assertions
from datetime import datetime

date_list = [
    datetime(2020, 8, 2, 15, 20, 30),
    datetime(2020, 8, 3, 12, 10, 15),
    datetime(2020, 8, 3, 8, 4, 45),
]

after_date = datetime(2020, 8, 1, 0, 0, 0)

with soft_assertions():
    for date in date_list:
        assert_that(date).is_after(after_date)

```

But when after_date is equal to one of dates ,  I am getting a problem:

```python
from assertpy import assert_that, soft_assertions
from datetime import datetime

date_list = [
    datetime(2020, 8, 2, 15, 20, 30),
    datetime(2020, 8, 3, 12, 10, 15),
    datetime(2020, 8, 3, 8, 4, 45),
]

after_date = datetime(2020, 8, 2, 15, 20, 30)

with soft_assertions():
    for date in date_list:
        assert_that(date).is_after(after_date)

>>>
AssertionError: soft assertion failures:
1. Expected <2020-08-02 15:20:30> to be after <2020-08-02 15:20:30>, but was not.
```

I understand that "is_after" has inside condition: if self.val <= other:
That's why I'm gettring this error.

I'm asking you to expand the library's ability to check dates by adding new methods, for example
is_after_includig
is_before_including

that will allow to check dates that's are equal to boundary condition values

**Comment by saturnboy** [comment]
@maxim-zaitsev you can use the _numeric_ assertions with `datetime` dates such as [is_greater_than_or_equal_to()](https://assertpy.github.io/docs.html#assertpy.numeric.NumericMixin.is_greater_than_or_equal_to) which does exactly what you want.
