### ISSUE TITLE
Allow extracting on 'namedtuple' objects

### ISSUE THREAD

**Issue by TomVanWemmel** [assertpy/assertpy#109]
The 'extracting' helper does not work for 'namedtuple' objects.

It would be great to support this behaviour: 

```python
from collections import namedtuple
from assertpy import assert_that

MyClass = namedtuple('MyClass', 'my_attribute')
classes = [MyClass('attribute_value_1'), MyClass('attribute_value_2')]

assert_that(classes).extracting('my_attribute').contains('attribute_value_1')
```

Currently, this would result in the following error:
`TypeError: tuple indices must be integers or slices, not str`

**Comment by saturnboy** [comment]
@TomVanWemmel great idea.  PR incoming?

**Comment by starhel** [comment]
There's probably more problems than `namedtuple`:
* any `Iterable` with `__getitem__` has precedense before `getattr`
* `__getitem__` is enough to get items, but `extracting` checks also for `isinstance(elem, Iterable)` so `__iter__` must be also defined

I have [dev version](https://github.com/starhel/assertpy/tree/fix-109) supporting both cases correctly (imho), if you want I can prepare PR.

**Comment by rodfersou** [comment]
@starhel yeah, this is the case of the Pydantic models, [created one pull request](https://github.com/assertpy/assertpy/pull/114) trying to make a fix.. but more generic fix would be desirable

**Comment by saturnboy** [comment]
FYI `namedtuple` extracting works perfectly using the tuple index for the field (just not the field name):

```py
from collections import namedtuple
from assertpy import assert_that

Foo = namedtuple('Foo', ['bar', 'baz'])
foos = [Foo(bar='abc', baz=123), Foo(bar='xyz', baz=456)]

# these both pass..
assert_that(foos).extracting(0).is_equal_to(['abc', 'xyz'])
assert_that(foos).extracting(1).is_equal_to([123, 456])
```
