### ISSUE TITLE
Is there any way to compare list of dicts excluding some dict keys (json properties in real api testing)

### ISSUE THREAD

**Issue by dimastick** [assertpy/assertpy#115]
We have
[
{'id': 1, 'contactId': 77, 'phone': 123},
{'id': 3, 'contactId': 78, 'phone': 124}
]
and
[
{'id': 7, 'contactId': 22, 'phone': 123},
{'id': 7, 'contactId': 23,  'phone': 124}
]

we need to compare them not taking into consideration neither "id" nor "contactId".
Could you please elaborate if it is possible. If so, in what way? Thank you in advance

**Comment by dimastick** [comment]
Could not find how to mark the case as a question.

**Comment by saturnboy** [comment]
@dimastick use `ignore` or `include` with `is_equal_to()` to include or exclude dict keys when comparing dicts.  See [Dict Comparison](https://github.com/assertpy/assertpy#dict-comparison) for details.

```py
l = [{'id': 1, 'contactId': 77, 'phone': 123}, {'id': 3, 'contactId': 78, 'phone': 124}]
l2 = [{'id': 7, 'contactId': 22, 'phone': 123}, {'id': 7, 'contactId': 23, 'phone': 124}]
for i,item in enumerate(l):
    item2 = l2[i]
    assert_that(item).is_equal_to(item2, ignore=['id', 'contactId'])
    # or: assert_that(item).is_equal_to(item2, include='phone')
```

**Comment by dimastick** [comment]
Thank you for the explanation. Closing the case
