### ISSUE TITLE
ContainsMixin - missing return of an AssertionBuilder instance if verification fails.

### ISSUE THREAD

**Issue by bestiasan** [assertpy/assertpy#116]
I've found that some methods in `ContainsMixin` (` is_in`, `contains_sequence`,` contains_duplicates`, `does_not_contain_duplicates`) doesn't return the instance of the AssertionBuilder chain if the verification fail.

There is an 'exception' problem when I try to use `asser_warn` with some of these methods:

```python
assert_warn(1).is_in(2).contains_duplicates()
```

```
WARNING [<input>:1]: Expected <1> to be in <2>, but was not.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'contains_duplicates'
```

**Comment by saturnboy** [comment]
Looks like a bug. Some assertions are using the `error()` helper by directly invoking the function, like this:
```py
self.error('Expected <%s> to contain duplicates, but did not.' % self.val)
```

Correct should be `return`ing the result of the helper, like this:
```py
return self.error('Expected <%s> to contain duplicates, but did not.' % self.val)
```

...and probably need some tests to ensure this works.
