### ISSUE TITLE
python 3.10 support 

### ISSUE THREAD

**Issue by artemijan** [assertpy/assertpy#119]
Hello, I'm using your library in my project, and
There is an issue with importing:
```
import Iterable from collections
```
It's deprecated in python 3.10
In the result this library doesn't work at all in python 3.10

**Comment by saturnboy** [comment]
@artemijan in all cases in `assertpy`, `Iterable` is imported as:

```py
import collections

if sys.version_info[0] == 3:
    Iterable = collections.abc.Iterable
else:
    Iterable = collections.Iterable
```

...I believe that import you are referencing must come from another project.
