### ISSUE TITLE
    def described_as(self, description): method signature returns "Any" instead of "AssertionBuilder"

### ISSUE THREAD

**Issue by mkienenb** [assertpy/assertpy#139]
I am a brand new python user, but a long time `assertJ` user.

I noticed that the latest version of PyCharm (PyCharm 2024.2.1 (Professional Edition)) cannot handle auto-completion after chaining described_as().

This appears to be due to the method signature return type of `described_as` being `def described_as(self, description: Any) -> Any` while the method signature of `assert_that` is `def assert_that(val: Any,
                description: Any = '') -> AssertionBuilder`

Am I understanding the problem correctly?  Maybe there is a reason why `described_as` has a more general return type, but it seems like restricting it to` AssertionBuilder` would fix autocompletion.

Apologies if I am totally off-base because of some misconception about how python works.

**Comment by saturnboy** [comment]
The majority of assertpy was written before types, and it still supports python 2.7 so types can't be easily added, but all modern editors like VSCode and PyCharm do their best to infer the correct types.

The `described_as()` method is implemented as:

```py
class BaseMixin(object):
    def described_as(self, description):
        self.description = str(description)
        return self
    ..
```

...so it certainly _does_ return `AssertionBuilder` (the `BaseMixin` is one of the many superclasses to `AssertionBuilder`), but I guess like the type inference in PyCharm is not getting you everything you need.

Here is a screenshot of a project in VSCode, you can see it correctly understands `described_as` returns `AssertionBuilder`:

<img width="663" alt="Screenshot 2024-09-07 at 10 51 35 AM" src="https://github.com/user-attachments/assets/8d94649f-fae6-473e-995f-f42fede5bf04">

...I'm sure modern IDE's are complex beasts, but seems like a PyCharm issue to me.

**Comment by mkienenb** [comment]
Thank you for looking into it and taking the time to explain to me.  You're right -- it does look like a PyCharm issue if it's working working VSCode.
